### ISSUE TITLE
Cannot decode TOML array into struct field schema.Config.DataDir

### ISSUE THREAD

**Issue by sveratum** [khairul169/garage-webui#1]
Hello,
Starting with Garage version 1.0.0 (or earlier) there is an option to specify disks as an array. But webui does not accept this configuration https://garagehq.deuxfleurs.fr/documentation/operations/multi-hdd/

Getting error: toml: cannot decode TOML array into struct field schema.Config.DataDir of type string

**Comment by apavlychev** [comment]
Also when we have created buckets then a list of buckets fall with a error `json: cannot unmarshal object into Go struct field GetBucketsRes.localAliases of type string`

**Comment by khairul169** [comment]
Hello @sveratum @apavlychev,

I apologize for the late response. I've published a fix for both issues in version `1.0.4`.
Please let me know if the problem persists.

Thank you! ^^
