### ISSUE TITLE
Make region configurable

### ISSUE THREAD

**Issue by zoop-btc** [khairul169/garage-webui#2]
Hi,

Making the region configurable would be a big help to me. If anybody has configured a different value than "garage" in the garage config they won't be able to use the client to browse otherwise.

https://github.com/khairul169/garage-webui/blob/611258d0dbd80fced31b2029d7ab3d5053c53913/backend/router/browse.go#L303

Thanks and regards,
Zoop

**Comment by khairul169** [comment]
Hi, good catch! totally slipped my mind to test s3_region outside of "garage" 😅. i'll get that sorted to match the config file. appreciate the heads up!
